name: Tailnet
# zizmor: ignore[excessive-permissions]
permissions:
  contents: read
  id-token: write
"on":
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch: {}
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/cache@v5
        with:
          key: version-cache.json-${{ github.run_id }}
          path: ./version-cache.json
          restore-keys: version-cache.json-
      - name: Validate policy
        uses: tailscale/gitops-acl-action@v1
        with:
          action: test
          audience: ${{ vars.TAILSCALE_AUDIENCE }}
          oauth-client-id: ${{ vars.TAILSCALE_OAUTH_CLIENT_ID }}
          tailnet: ${{ vars.TAILSCALE_TAILNET }}
  apply:
    if: ${{ github.event_name != 'pull_request' }}
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v6
      - name: Sync policy
        uses: tailscale/gitops-acl-action@v1
        with:
          action: apply
          audience: ${{ vars.TAILSCALE_AUDIENCE }}
          oauth-client-id: ${{ vars.TAILSCALE_OAUTH_CLIENT_ID }}
          tailnet: ${{ vars.TAILSCALE_TAILNET }}
